twitch-info:
  # This is your Twitch oauth token. You can generate one here: https://twitchapps.com/tmi/
  # Messages will be sent using this account. You can create another Twitch account and use its token if you want the messages to come from another user.
  token: 'oauth:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

  # This is the name of the channel you want to connect to. Leave this as '' to connect to the channel logged into from the token.
  channel-name: ''

# Command prefix for the Twitch bot. This is the prefix that the bot will use to identify commands, and all add-ons will use this prefix as well.
twitch-command-prefix: '!'

share-chat:
  twitch-to-minecraft:
    # true/false: Whether or not to broadcast Twitch chat in your Minecraft chat.
    enabled: true
    
    format:
      # The format that will be used if the player has NOT linked their Twitch account to their Minecraft account. Color codes are supported using the & symbol. You can use the following variables:
      # %twitch% - The Twitch name
      # %twitch-color% - The Twitch user's color code
      # %message% - The message that was sent
      unlinked: '&7[&#9146FFTW&7] %twitch-color%%twitch%&7: &f%message%'
      
      # The format that will be used if the player has linked their Twitch account to their Minecraft account. You can use the variables from above as well as:
      # %player% - The Twitch user's Minecraft name
      linked: '&7[&#9146FFTW&7] %twitch-color%%twitch%&7 &8(%player%)&7: &f%message%'

    # If true, the bot not share messages to Minecraft chat if the message starts with the Twitch bot's command prefix (specified in twitch-command-prefix)
    ignore-commands: true
    
  minecraft-to-twitch:
    # true/false: Whether or not to broadcast Minecraft chat in your Twitch chat.
    enabled: true

    format:
      # The format that will be used if the player has NOT linked their Twitch account to their Minecraft account. You can use the following variables:
      # %player% - The player's name
      # %message% - The message that was sent
      unlinked: '[MC] %player%: %message%'

      # The format that will be used if the player has linked their Twitch account to their Minecraft account. You can use the variables from above as well as:
      # %twitch% - The player's Twitch name
      linked: '[MC] %player% (%twitch%): %message%'

# The amount of time in minutes that the plugin will wait between each data save, which updates the database and frees up memory.
# The lower the number, the more CPU usage will be used (it will not be much if at all). If the server is unexpectedly shut down
# (i.e. a crash or power loss), the plugin will roll back to the last save. You can think of this as an "auto-save" interval.
flush-interval: 10

mysql:
  # Whether or not to use MySQL. If this is set to false, the plugin will use SQLite and ignore the rest of the MySQL settings below.
  enabled: false
  # The host of the MySQL server.
  host: localhost
  # The port of the MySQL server.
  port: 3306
  # The name of the database to use.
  database: minetwitch
  # The username to use to connect to the database.
  username: root
  # The password to use to connect to the database.
  password: password
