main: me.okay.minetwitch.MinetwitchPlugin
name: MineTwitch
version: 1.0
author: okay
api-version: 1.20

commands:
  minetwitch:
    description: "Manage the minetwitch plugin."
    usage: "/minetwitch"

permissions:
  # General permissions
  minetwitch.broadcast:
    description: "Whether players can broadcast or read messages to/from Twitch chat."
    default: true
    children:
      minetwitch.broadcast.twitch-to-minecraft: true
      minetwitch.broadcast.minecraft-to-twitch: true

  minetwitch.broadcast.twitch-to-minecraft:
    description: "Whether players can see messages from Twitch chat in Minecraft chat."
    default: true

  minetwitch.broadcast.minecraft-to-twitch:
    description: "Whether or not Minecraft messages from this player will broadcast to Twitch chat."
    default: true

  # Command permissions
  minetwitch.command.link:
    description: "Allows players to link their Twitch account to their Minecraft account using /minetwitch link."
    default: true

  minetwitch.admin.command:
    description: "Allows the usage of all admin commands."
    default: op
    children:
      minetwitch.admin.command.reload: true
      minetwitch.admin.command.broadcast: true

  minetwitch.admin.command.reload:
    description: "Allows players to reload MineTwitch using /minetwitch reload."
    default: op
  
  minetwitch.admin.command.broadcast:
    description: "Allows players to enable/disable the broadcasting of twitch to minecraft chat or vice versa using /minetwitch broadcast."
    default: op
    children:
      minetwitch.admin.command.broadcast.twitch-to-minecraft: true
      minetwitch.admin.command.broadcast.minecraft-to-twitch: true
  
  minetwitch.admin.command.broadcast.twitch-to-minecraft:
    description: "Allows players to enable/disable the broadcasting of twitch to minecraft chat."
    default: op

  minetwitch.admin.command.broadcast.minecraft-to-twitch:
    description: "Allows players to enable/disable the broadcasting of minecraft to twitch chat."
    default: op

