main: me.okay.minetwitch.Minetwitch
name: MineTwitch
version: 1.0
author: okay
api-version: 1.19

commands:
  minetwitch:
    description: "Manage the minetwitch plugin."
    usage: "/minetwitch"

permissions:
  minetwitch.admin:
    description: "Allows use of all MineTwitch commands."
    default: op
    children:
      minetwitch.reload: true
      minetwitch.broadcast: true

  minetwitch.reload:
    description: "Allows players to reload MineTwitch."
    default: op
  
  minetwitch.broadcast:
    description: "Allows players to enable/disable the broadcasting of twitch to minecraft chat or vice versa."
    default: op
    children:
      minetwitch.broadcast.twitch-to-minecraft: true
      minetwitch.broadcast.minecraft-to-twitch: true
  
  minetwitch.broadcast.twitch-to-minecraft:
    description: "Allows players to enable/disable the broadcasting of twitch to minecraft chat."
    default: op

  minetwitch.broadcast.minecraft-to-twitch:
    description: "Allows players to enable/disable the broadcasting of minecraft to twitch chat."
    default: op

  minetwitch.chatvisibility:
    description: "Allows players to configure who can see Twitch chat in Minecraft."
    default: op
    children:
      minetwitch.chatvisibility.broadcast-to-everyone: true
      minetwitch.chatvisibility.exceptions: true
    
  minetwitch.chatvisibility.broadcast-to-everyone:
    description: "Allows players to enable/disable whether or not everyone can see Twitch chat in Minecraft."
    default: op

  minetwitch.chatvisibility.exceptions:
    description: "Allows players to add or remove players to and from the visibility exceptions list."
    default: op